apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 183631308419.dkr.ecr.us-east-1.amazonaws.com/frontend:2
        ports:
        - containerPort: 80

